### ISSUE TITLE
Error when importing library, due to 'missing' FindOptions interface in sdk 

### ISSUE THREAD

**Issue by hidde-jan** [jolocom/sdk-storage-typeorm#17]
When I try to import the sdk-storage-typerorm into a typescript project, I get the following error:

```
node_modules/@jolocom/sdk-storage-typeorm/js/src/index.d.ts:1:47 - error TS2305: Module '"../../../sdk/js/storage"' has no exported member 'FindOptions'.
```

Indeed, the js file does not contain the FindOptions interface (since those don't exist in js), and the interface is instead located in the `index.d.ts` file in the same directory.

I'm not sure if this is an issue of this library, or if the sdk is not exporting their types correctly.

**Comment by mnzaki** [comment]
You probably just need to update your `@jolocom/sdk`

**Comment by hidde-jan** [comment]
I've checked what the issue was. After upgrading to node 14 and the newest version of typescript (4.2 from 3.9) the issue was solved. I was already running the latest versions of this library and the sdk.

Issue was solved though. Thanks!
