### ISSUE TITLE
Integer column used for timestamps are not large enough on postgres

### ISSUE THREAD

**Issue by hidde-jan** [jolocom/sdk-storage-typeorm#8]
See https://github.com/jolocom/sdk-storage-typeorm/blob/master/src/entities/encryptedWalletEntity.ts#L9

The timestamp is millisecond based, which is a lot bigger than the max you can store in a postgres integer column, which is 2^31-1.

**Comment by Exulansis** [comment]
Thank you for reporting the issue.
The issue has been addressed, and a new version of this module was released (at v4.0.0) on npm.

Please let us know if this solved your issue. If yes, we can close this ticket.

**Comment by mnzaki** [comment]
Fixed and there's a simple test added for ensuring postgres compatibility in the future
